"use client";

import Sidebar from "../../../components/Sidebar";
import Navbar from "../../../components/Navbar";
import { AlertTriangle, ArrowRight, PackageCheck } from "lucide-react";

const recommendations = [
  {
    id: 1,
    title: "Reorder Rice",
    priority: "High",
    category: "Inventory",
    action: "Order 50 more units",
    impact: "Prevents stock-out in 3 days",
    description:
      "Rice inventory is running low and demand is increasing.",
  },
  {
    id: 2,
    title: "Transfer Stock",
    priority: "Medium",
    category: "Warehouse",
    action: "Move 30 units to Warehouse A",
    impact: "Balances warehouse inventory",
    description:
      "Warehouse B has excess stock while Warehouse A is running low.",
  },
  {
    id: 3,
    title: "Reduce Overstock",
    priority: "Low",
    category: "Inventory",
    action: "Run a discount campaign",
    impact: "Reduces storage cost",
    description:
      "Cooking Oil has higher-than-required inventory.",
  },
];

export default function AIRecommendationsPage() {
  return (
    <div className="flex min-h-screen bg-black">
      <Sidebar />

      <div className="flex-1">
        <Navbar />

        <main className="p-8">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-white">
              AI Recommendations
            </h1>

            <p className="mt-2 text-zinc-500">
              Smart recommendations generated by AIVA.
            </p>
          </div>

          <div className="space-y-6">
            {recommendations.map((item) => (
              <div
                key={item.id}
                className="rounded-2xl border border-zinc-800 bg-zinc-950 p-6"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-xl font-semibold text-white">
                      {item.title}
                    </h2>

                    <p className="mt-1 text-sm text-zinc-500">
                      {item.description}
                    </p>
                  </div>

                  <span
                    className={`rounded-full px-4 py-1 text-sm font-medium ${
                      item.priority === "High"
                        ? "bg-red-500/20 text-red-400"
                        : item.priority === "Medium"
                        ? "bg-yellow-500/20 text-yellow-400"
                        : "bg-green-500/20 text-green-400"
                    }`}
                  >
                    {item.priority}
                  </span>
                </div>

                <div className="mt-6 grid gap-4 md:grid-cols-3">
                  <div className="rounded-xl bg-zinc-900 p-4">
                    <PackageCheck className="mb-2 text-blue-400" size={20} />
                    <p className="text-xs text-zinc-500">Category</p>
                    <p className="text-white">{item.category}</p>
                  </div>

                  <div className="rounded-xl bg-zinc-900 p-4">
                    <ArrowRight className="mb-2 text-green-400" size={20} />
                    <p className="text-xs text-zinc-500">Recommended Action</p>
                    <p className="text-white">{item.action}</p>
                  </div>

                  <div className="rounded-xl bg-zinc-900 p-4">
                    <AlertTriangle className="mb-2 text-orange-400" size={20} />
                    <p className="text-xs text-zinc-500">Estimated Impact</p>
                    <p className="text-white">{item.impact}</p>
                  </div>
                </div>

                <button className="mt-6 rounded-xl bg-white px-5 py-2 font-medium text-black transition hover:bg-zinc-200">
                  Take Action
                </button>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}